// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruY3SwN0XXTY_84yE9R1w6eIaB_kYvm0',
    appId: '1:455086253822:web:39a5c6105ad2ebbb3a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    authDomain: 'trim-time-b71fa.firebaseapp.com',
    storageBucket: 'trim-time-b71fa.appspot.com',
    measurementId: 'G-T6TXK6T80W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABryRwgRE-v0q94DsHqlgK01t9t5c5UR8',
    appId: '1:455086253822:android:9d68583ce78608653a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    storageBucket: 'trim-time-b71fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYLrtvbbvnpLUp0vhyaZIuvre6-rrnw8',
    appId: '1:455086253822:ios:ef8f59ff5c8197493a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    storageBucket: 'trim-time-b71fa.appspot.com',
    iosBundleId: 'com.example.trimTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJYLrtvbbvnpLUp0vhyaZIuvre6-rrnw8',
    appId: '1:455086253822:ios:ef8f59ff5c8197493a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    storageBucket: 'trim-time-b71fa.appspot.com',
    iosBundleId: 'com.example.trimTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAruY3SwN0XXTY_84yE9R1w6eIaB_kYvm0',
    appId: '1:455086253822:web:bd6a00ae2adb9b5d3a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    authDomain: 'trim-time-b71fa.firebaseapp.com',
    storageBucket: 'trim-time-b71fa.appspot.com',
    measurementId: 'G-L9K21LTYQL',
  );

}