// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpJvk8LAz5pbC1icxbtsWhxdvciCtctc',
    appId: '1:132866959008:web:1470ed8ca95d15c2c20bc5',
    messagingSenderId: '132866959008',
    projectId: 'trim-time-ae996',
    authDomain: 'trim-time-ae996.firebaseapp.com',
    storageBucket: 'trim-time-ae996.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVrpM3Y5cdiYVa-j-UYMdyv0koEuEEdY',
    appId: '1:132866959008:android:9880c22cf2794398c20bc5',
    messagingSenderId: '132866959008',
    projectId: 'trim-time-ae996',
    storageBucket: 'trim-time-ae996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYLrtvbbvnpLUp0vhyaZIuvre6-rrnw8',
    appId: '1:455086253822:ios:ef8f59ff5c8197493a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    storageBucket: 'trim-time-b71fa.appspot.com',
    iosBundleId: 'com.example.trimTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJYLrtvbbvnpLUp0vhyaZIuvre6-rrnw8',
    appId: '1:455086253822:ios:ef8f59ff5c8197493a27af',
    messagingSenderId: '455086253822',
    projectId: 'trim-time-b71fa',
    storageBucket: 'trim-time-b71fa.appspot.com',
    iosBundleId: 'com.example.trimTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPpJvk8LAz5pbC1icxbtsWhxdvciCtctc',
    appId: '1:132866959008:web:d0378187dbf12b24c20bc5',
    messagingSenderId: '132866959008',
    projectId: 'trim-time-ae996',
    authDomain: 'trim-time-ae996.firebaseapp.com',
    storageBucket: 'trim-time-ae996.appspot.com',
  );

}